# TO-DO: set up reusable action for cleaner terraform_run.yml

name: 'Prep Terraform Run'
description: 'Setup terraform and configure AWS credentials'
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'The AWS access key id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'The AWS secret access key'
    required: true
  S3_BACKEND_BUCKET:
    description: 'The S3 bucket where our remote backend lives'
    required: true
  S3_BACKEND_KEY:
    description: 'The name of our state file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup terraform
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.11.4"
    
    - name: Terraform init
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.S3_BACKEND_BUCKET }}" \
          -backend-config="key=${{ inputs.S3_BACKEND_KEY }}"